name: Build Envoy
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build-Envoy
    runs-on: ubuntu-latest
    env:
      cache-dir: ~/envoy_cache
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache compilation
        uses: actions/cache@v3
        env:
          cache-name: test-cache-compilation
        with:
          path: ${{ env.cache-dir }}
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Run build-envoy
        run: |
          ENVOY_DOCKER_BUILD_DIR=${{ env.cache-dir }} ./ci/run_envoy_docker.sh make build-envoy 'BUILD_OPTS="--define=deprecated_features=disabled --define=wasm=disabled"' 'COMPILE_MODE=fastbuild'
